version: "3"
services:
    proxy:
        image: nginx:latest # 최신 버전의 Nginx 사용
        container_name: proxy # container 이름은 relay
        ports:
            - "8001:8001" # 80번 포트를 host와 container 맵핑
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf # nginx 설정 파일 volume 맵핑
        restart: "unless-stopped" # 내부에서 에러로 인해 container가 죽을 경우 restart
    nodeserver:
        container_name: nodeserver
        build: ./nodeServer
        # restart: always
        env_file:
            # - ./nodeServer/.env
            # - ./nodeServer/restServer/.env
        expose:
            - "8081"
    nodeserver2:
        container_name: nodeserver2
        build: ./nodeServer2
        # restart: always
        env_file:
            # - ./nodeServerenv/.env
            # - ./nodeServerenv/restServer/.env
        expose:
            - "8082"
